# Generated by Django 4.2.7 on 2025-05-06 19:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('descricao_curta', models.TextField(max_length=300)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('imagem_principal', models.ImageField(upload_to='eventos/')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('descricao', ckeditor.fields.RichTextField()),
                ('imagem_principal', models.ImageField(upload_to='portfolio/')),
                ('destaque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Projeto do Portfólio',
                'verbose_name_plural': 'Projetos do Portfólio',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao_curta', models.TextField(max_length=300)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('icone', models.CharField(help_text='Nome do ícone Font Awesome (ex: fa-calendar)', max_length=50)),
                ('imagem', models.ImageField(upload_to='servicos/')),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='tipos_eventos/')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='ImagemPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='portfolio/')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='eventos.portfolio')),
            ],
            options={
                'verbose_name': 'Imagem do Portfólio',
                'verbose_name_plural': 'Imagens do Portfólio',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ImagemEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='eventos/')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Imagem do Evento',
                'verbose_name_plural': 'Imagens dos Eventos',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.tipoevento'),
        ),
    ]
