# Generated by Django 4.2.7 on 2025-05-06 19:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('texto_botao', models.CharField(blank=True, max_length=30, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='site/')),
                ('favicon', models.ImageField(upload_to='site/')),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField()),
                ('horario_funcionamento', models.CharField(max_length=200)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('descricao_meta', models.CharField(help_text='Descrição para SEO (máximo 160 caracteres)', max_length=160)),
                ('palavras_chave', models.CharField(help_text='Palavras-chave separadas por vírgula', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('data', models.DateField(auto_now_add=True)),
                ('destaque', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('foto', models.ImageField(upload_to='equipe/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Equipe',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('resposta', ckeditor.fields.RichTextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='parceiros/')),
                ('website', models.URLField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SobreNos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('texto', ckeditor.fields.RichTextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sobre/')),
                ('video_url', models.URLField(blank=True, help_text='URL do vídeo do YouTube', null=True)),
            ],
            options={
                'verbose_name': 'Sobre Nós',
                'verbose_name_plural': 'Sobre Nós',
            },
        ),
    ]
